### ISSUE TITLE
你好，请问怎么修改转发的端口，不重启进程的话

### ISSUE THREAD

**Issue by ilovebamboo** [zhc105/Liteflow#1]
RT
你好，请问怎么修改转发运行的端口?
不重启进程的话
Hello, may I ask how to modify the running forwarding port?
Do not restart the process

**Comment by zhc105** [comment]
抱歉，目前程序不支持不重启修改配置，如果增加一个SignalHandler, 增加一个reload config功能应该是可以做到的，我以后可能会改一下。

**Comment by ilovebamboo** [comment]
这个可以和udpspeeder 结合使用吗？我尝试过 但是没有活动

**Comment by ilovebamboo** [comment]
我想付款 500请您解决一下

**Comment by ilovebamboo** [comment]
> 抱歉，当前程序不支持不重启修改配置，如果增加一个SignalHandler，增加一个重新加载配置功能应该是可以做到的，我以后可能会改一下。

加一下wx:zengjian0007

**Comment by zhc105** [comment]
我不太建议和udpspeeder一起用，因为liteflow本身自己也有FEC。另外reload config这个功能我这周会加上的，付款的话就不需要啦。感谢支持~ :)

**Comment by ilovebamboo** [comment]
付款也是对这个很认可，确实有效。低调使用。
![image](https://user-images.githubusercontent.com/6214084/68589399-c1391200-04c6-11ea-90a7-17d719cc1bc5.png)
![image](https://user-images.githubusercontent.com/6214084/68589422-cdbd6a80-04c6-11ea-98cb-756f56d2cff7.png)

最好像nginx.conf 一样可以reload前 做1次检查
![image](https://user-images.githubusercontent.com/6214084/68590345-41f90d80-04c9-11ea-9dee-2896552985ee.png)
------------
user  nginx;
worker_processes  1;
worker_rlimit_nofile 65535;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  65535;
}

stream {
    tcp_nodelay on;
	proxy_upload_rate 502400;
    server {
        listen 3267;
        proxy_pass 119.96.128.117:3267;
    }
    server {
        listen 3267 udp;
        proxy_pass 119.96.128.117:3267;
    }
}

**Comment by ilovebamboo** [comment]
目前我Nginx还遇到一个问题(玩游戏掉线厉害 Nginx 超时访问拒绝) 我现在200个IP 200个端口/连接数500-1000，并发数量在60000左右，不知道能不能承受。

**Comment by zhc105** [comment]
现在可以通过命令：
kill -SIGUSR1 $(liteflow_pid)
重新加载配置文件
