### ISSUE TITLE
速度设置有点问题

### ISSUE THREAD

**Issue by qqnr88** [zhc105/Liteflow#35]
服务器端设置"transmit_rate_max": 102400  客户端没有设置的话 感觉这个不会有效，
如果客户端设置"transmit_rate_max": 服务器端不设置的话，可以限定到指定的速度，如何在服务器端限制这个传输速率？

**Comment by zhc105** [comment]
这个设置的作用是限制最大发包频率，所以是对发送方生效的。例如：如果你的主要场景是从服务端向客户端发送数据，同时你不希望服务端发包速度超过10MB/s，则应该在服务端将这个值配置为"transmit_rate_max": 10485760

**Comment by qqnr88** [comment]
> 这个设置的作用是限制最大发包频率，所以是对发送方生效的。例如：如果你的主要场景是从服务端向客户端发送数据，同时你不希望服务端发包速度超过10MB/s，则应该在服务端将这个值配置为"transmit_rate_max": 10485760

感谢讲解
